# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_tracks', '0005_musictrack_name_es'),
        ('music_packs', '0005_musicpack_name_es'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(null=True)),
                ('amount', models.FloatField()),
                ('music_packs', models.ManyToManyField(to='music_packs.MusicPack')),
                ('music_tracks', models.ManyToManyField(to='music_tracks.MusicTrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
