# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='deleted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
