# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_remove_tag_level'),
        ('categories', '0002_auto_20170912_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('short_description', models.TextField(max_length=160)),
                ('long_description', models.TextField(max_length=2000)),
                ('image', models.ImageField(null=True, upload_to='music_tracks')),
                ('price', models.FloatField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
