# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_tracks', '0003_musictrack_price'),
        ('music_packs', '0002_auto_20170917_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpack',
            name='music_tracks',
            field=models.ManyToManyField(to='music_tracks.MusicTrack'),
        ),
    ]
