# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_packs', '0003_musicpack_music_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpack',
            name='long_description_es',
            field=models.TextField(default='_', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicpack',
            name='short_description_es',
            field=models.TextField(default='_', max_length=160),
            preserve_default=False,
        ),
    ]
