# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170806_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.TextField(max_length=400, null=True, unique=True),
        ),
    ]
