# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20170912_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image_url',
            new_name='image',
        ),
    ]
