# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20170912_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='authors'),
        ),
    ]
