# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_auto_20170917_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description_es',
            field=models.TextField(default=' ', max_length=800),
            preserve_default=False,
        ),
    ]
