# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('image_url', models.TextField(max_length=300, null=True)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('level', models.IntegerField()),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_track.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrackCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_track.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrackTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('name', models.TextField(max_length=200)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='music_track.Author')),
                ('short_description', models.TextField(max_length=120)),
                ('long_description', models.TextField(max_length=300)),
                ('duration', models.TimeField()),
                ('image_url', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='musictracktag',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_track.Tag'),
        ),
        migrations.AddField(
            model_name='musictracktag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_track.MusicTrack'),
        ),
        migrations.AddField(
            model_name='musictrackcategory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_track.MusicTrack'),
        ),
    ]
