# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_packs', '0005_musicpack_name_es'),
        ('tags', '0003_tag_name_es'),
        ('authors', '0006_author_description_es'),
        ('categories', '0003_category_name_es'),
        ('music_tracks', '0005_musictrack_name_es'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('name_es', models.TextField(max_length=200)),
                ('short_description', models.TextField(max_length=160)),
                ('intro', models.TextField(max_length=2000)),
                ('intro_es', models.TextField(max_length=160)),
                ('post', models.TextField()),
                ('post_es', models.TextField()),
                ('image', models.ImageField(upload_to='blog')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('music_packs', models.ManyToManyField(to='music_packs.MusicPack')),
                ('music_tracks', models.ManyToManyField(to='music_tracks.MusicTrack')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
