# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='music_packs',
            field=models.ManyToManyField(blank=True, to='music_packs.MusicPack'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='music_tracks',
            field=models.ManyToManyField(blank=True, to='music_tracks.MusicTrack'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
