# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('name', models.TextField(max_length=200)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authors.Author')),
                ('short_description', models.TextField(max_length=120)),
                ('long_description', models.TextField(max_length=300)),
                ('duration', models.TimeField()),
                ('image_url', models.TextField(max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
