# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_tracks', '0002_auto_20170917_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
