# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_tracks', '0004_auto_20170918_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='name_es',
            field=models.TextField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
