# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170912_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.TextField(default='_', max_length=200),
            preserve_default=False,
        ),
    ]
